# Generated by Django 4.2.30 on 2026-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on homepage preview'),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='Core lab — cannot be deleted'),
        ),
    ]
